SELECT ROK, RAZEM, 
	LAST_VALUE(SUM(PROCENT))
		OVER(
			PARTITION BY ROK
			ORDER BY ROK
			ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) 
		AS PROCENT 
FROM (
SELECT
	CASE WHEN GROUPING(DATA_PRZYZNANIA)=1 THEN 'RAZEM' 
       ELSE to_char(EXTRACT(YEAR FROM DATA_PRZYZNANIA)) END AS ROK,
	SUM(SUM(KWOTA)) OVER(
		PARTITION BY EXTRACT(YEAR FROM DATA_PRZYZNANIA)
		ORDER BY DATA_PRZYZNANIA
			ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
	AS RAZEM,
	ROUND(100*2*SUM(KWOTA)/SUM(SUM(KWOTA)) OVER(
		ORDER BY DATA_PRZYZNANIA
			RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING),2)
	AS PROCENT
FROM SWIADCZENIA
GROUP BY ROLLUP (DATA_PRZYZNANIA)
)
GROUP BY ROK, RAZEM
ORDER BY ROK;